language: node_js
node_js:
  - 10
cache:
  directories:
    - 'node_modules'
jobs:
  include:
    install:
      - npm install
    script:
      - npm run build
    if: type = pull_request
    script:
      - docker build .
