language: node_js
node_js:
  - 10
cache:
  directories:
    - 'node_modules'

stages:
  - build
  - test
  - name: build-image
    if: type = pull_request

install:
  - npm install

jobs:
  include:
    - stage: build
      script: npm run build
    - stage: test
      script: npm run test
    - stage: build-image
      script: docker build .
